# docker/docker-compose.yml
services:

  uql:
    image: uql:latest
    container_name: uql
    restart: unless-stopped
    ports:
      - "20001:20001"
    expose:
      - "20001"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=20001
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs