version: '3'

services:
  uql:
    build:
      context: "./uql"
      target: "production"
    image: "uql:${TAG:-latest}"
    container_name: uql
    ports:
      - "20001:20001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 